### ISSUE TITLE
[BUG] crash when waking up (4.0.3) (4.0.4)

### ISSUE THREAD

**Issue by Jonah-Hansen** [SaltSouls/Calm-Mornings#36]
**Describe the Bug:**
Crash when waking up

1.19.2 calm mornings 4.0.3

Default config file

We've had a few reports of this happening from players of our modpack, not sure of the exact steps/what the common factor is for it happening vs not

https://mclo.gs/r5LTtsq

**To Reproduce:**
1. Sleep
2. Wake up
3. Crash

**Expected Behavior:**
Waking from sleep should despawn mobs, and not crash

**Version (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.4.12
 - Mod: 4.0.3

**Log Files:**
https://mclo.gs/r5LTtsq

**Comment by Jonah-Hansen** [comment]
One user said curseforge "repair profile" fixed is as it was after updating from a previous version that it occured

**Comment by SaltSouls** [comment]
I am not getting this crash. Is this happening when only this mod is installed?

I should also not that the reasoning for the crash seems to be because of a ticking world exception, which my mod doesn't touch world tick.

**Comment by Jonah-Hansen** [comment]
I'll try to get more info from people who it happens to (haven't personally experienced it, just getting reports from players of our modpack, but its only happened after updating calm mornings from 2.0.2 -> 4.0.3)

I should also mention the problem is resolved by removing calm mornings from the pack

**Comment by SaltSouls** [comment]
Does the crash only occur when there is another player around when sleeping and then waking up?

**Comment by Jonah-Hansen** [comment]
so far reports are only for singleplayer

**Comment by SaltSouls** [comment]
Hmmm... It could have to do with the fact that the old version has already created a datapack/added tags to the player, and the new version, being that it is a completely different code base at this point, is looking at those and freaking out because it has no idea what to make of them. Can you ask one of the players experiencing this crash to try creating a fresh world and see if it still occurs?

**Comment by Jonah-Hansen** [comment]
sounds like a promising theory. one report said the curseforge "repair profile" button fixed it... 

doesn't seem to occur on fresh install. I'll make a note in our changelog. thanks for your help!

**Comment by Jonah-Hansen** [comment]
hey, just got a report that it happened with a fresh install. awaiting more details from the player.

here is another crash log. https://mclo.gs/iHffjga

**Comment by SaltSouls** [comment]
If you can find out what mod this is conflicting with, please let me know so that I can fix the issue, or at least reach out to the dev to work with them on a fix. Right now there are too many mods to tell what is actually causing the issue.

**Comment by SaltSouls** [comment]
> hey, just got a report that it happened with a fresh install. awaiting more details from the player.
> 
> here is another crash log. https://mclo.gs/iHffjga

I haven't heard back in a little while. Is this issue still occuring? If so, could you send me the modpack so that I can take a look and test myself?

**Comment by SaltSouls** [comment]
> hey, just got a report that it happened with a fresh install. awaiting more details from the player.
> 
> here is another crash log. https://mclo.gs/iHffjga

Could you please have one of the players experiencing crashing try this version? I believe I have fixed it, but I need to makes sure it isn't just for me. They will have to unzip it as for whatever reason Github won't allow me to directly upload the jar file.

[calmmornings-1.19.4-4.0.zip](https://github.com/user-attachments/files/18533977/calmmornings-1.19.4-4.0.zip)

**Comment by SaltSouls** [comment]
Closing this unless there is something I missed. Currently, it would appear the issue has been fixed in [5f8b48e](https://github.com/SaltSouls/Calm-Mornings/commit/5f8b48e857f8f6eb4ef38717c94e030c6d5a266a).

**Comment by Jonah-Hansen** [comment]
sorry to keep bugging you but I continue to get some crashes. most seem to be fixed with 4.0.4 but finally got a log for one on singleplayer still crashing even with the update 

https://mclo.gs/4UidgLf

had them remove xaeros too as I see it coming up in the stacktrace, which seemed to help.

update: adding back xaeros did not reintroduce the crash

**Comment by SaltSouls** [comment]
> sorry to keep bugging you but I continue to get some crashes. most seem to be fixed with 4.0.4 but finally got a log for one on singleplayer still crashing even with the update
> 
> https://mclo.gs/4UidgLf
> 
> had them remove xaeros too as I see it coming up in the stacktrace, which seemed to help.
> 
> update: adding back xaeros did not reintroduce the crash

Given that apparently there were some pretty big changes between 1.19/1.19.2 and 1.19.3/1.19.4, I might have to split of the version of my mod to have a specific version for that version of the game. I'll give it another look and see if I can figure out what exactly is causing the crash this time, and if it can be addressed without having to split the 1.19 version of the mod in two.

EDIT: I'm gonna have to split it. Apparently a major function that the 1.19.4 version uses, is not there for 1.19.2 and lower. I will update you here when I have completed the new version for 1.19.2 and below.

**Comment by SaltSouls** [comment]
Alright. The most recent changes, creating a whole new branch for 1.19.2 and below, should fix any problems with the 1.19.2 version of the mod. Just need to post it to modrinth/curseforge and we should be good to go. Closing this for now unless a new issue(hopefully not this time) arises.

**Comment by Jonah-Hansen** [comment]
I have a crash log here from 4.0.5...  wish I had time/was able to recreate myself to investigate directly 😭 

2 players on a dedicated server, both clients and server have calm mornings updated to 4.0.5.

user claims it does not happen every time. initially was just one user client crashing but this log is when it took the whole server down. sounds like it may be more common when one player waits in bed for a while before the second player goes to sleep, then still crashing as morning arrives

https://mclo.gs/PqA1ymx

feel free to join our server and I can ping you in crash reports so you can work directly with players for troubleshooting. but if this seems to continue by the time we are ready for our next release we may just need to remove calm mornings altogether for now.

https://discord.gg/3ctFZ6KKb8

**Comment by SaltSouls** [comment]
You guys are really putting me and my mod through the ringer. I'm at least happy you're actually reporting it rather than just removing the mod. I'll jump into the discord and start asking some questions to figure out exactly what is going on when the crashes are occurring so that I can properly kill this once and for all.
